# ==============================================================================
# Help target
# ==============================================================================

.PHONY: help
help:
	@echo "Available targets:"
	@echo ""
	@echo "Build & Development:"
	@echo "  build          - Build debug version"
	@echo "  release        - Build release version"
	@echo "  check          - Check code without building"
	@echo "  clean          - Clean build artifacts"
	@echo "  doc            - Generate and open documentation"
	@echo "  install        - Install binary locally"
	@echo "  uninstall      - Uninstall binary"
	@echo ""
	@echo "Code Quality:"
	@echo "  fmt            - Format code"
	@echo "  fmt-check      - Check formatting"
	@echo "  lint           - Run clippy linter"
	@echo "  lint-all       - Run clippy on all targets"
	@echo "  ci             - Run all CI checks"
	@echo "  watch          - Watch and run tests"
	@echo ""
	@echo "Testing:"
	@echo "  test           - Run all tests"
	@echo "  test-verbose   - Run tests with output"
	@echo "  test-one TEST=x - Run specific test"
	@echo "  validate-fixtures        - Validate all test fixtures"
	@echo "  validate-fixtures-detail - Detailed validation results"
	@echo "  validate-all-rules       - Test each rule with its fixture"
	@echo ""
	@echo "CLI Usage Examples:"
	@echo "  run            - Run CLI with sample file"
	@echo "  run-args ARGS  - Run CLI with args"
	@echo "  yaml-lint FILE=x.yaml    - Lint a single file"
	@echo "  yaml-lint-dir DIR=path/  - Lint a directory"
	@echo "  yaml-lint-examples       - Lint examples directory"
	@echo "  yaml-lint-strict         - Lint with strict mode"
	@echo "  yaml-lint-config CONFIG=x FILE=y - Lint with custom config"
	@echo "  yaml-lint-relaxed        - Lint with relaxed preset"
	@echo "  yaml-lint-parsable       - Lint with parsable output"
	@echo "  yaml-lint-colored        - Lint with colored output"
	@echo "  yaml-lint-list           - List files that would be linted"
	@echo "  yaml-lint-help           - Show CLI help"
	@echo ""
	@echo "Release:"
	@echo "  version        - Show current version"
	@echo "  bump-patch     - Bump patch version (0.1.0 -> 0.1.1)"
	@echo "  bump-minor     - Bump minor version (0.1.0 -> 0.2.0)"
	@echo "  bump-major     - Bump major version (0.1.0 -> 1.0.0)"
	@echo "  set-version V=x.y.z  - Set specific version"
	@echo "  release-build  - Build optimized release binary"
	@echo "  release-target TARGET=x - Build for specific target"
	@echo "  dist-package   - Package binary for current platform"
	@echo "  dist-checksums - Generate SHA256 checksums"
	@echo "  dist-clean     - Clean dist directory"
	@echo "  tag            - Create git tag for current version"
	@echo "  tag-push       - Push tag to remote"
	@echo "  tags           - List all tags"
	@echo "  release-prepare      - Run all checks before release"
	@echo "  release-create       - Create and push release"
	@echo "  release-checklist    - Show release checklist"
	@echo "  release-install      - Install to /usr/local/bin"
	@echo "  release-uninstall    - Uninstall from /usr/local/bin"
	@echo "  release-size   - Show binary size"
	@echo "  release-info   - Show binary info"
	@echo "  release-strip  - Strip debug symbols"
	@echo ""
	@echo "Other:"
	@echo "  update         - Update dependencies"
	@echo "  outdated       - Check for outdated dependencies"
	@echo "  audit          - Security audit"
	@echo "  deps           - Show dependency tree"
	@echo "  help           - Show this help"
